menu:
  postlist: "文章列表"
  tag: "标签"
  welcome: "欢迎"
  myinfo: "我的信息"
  myposts: "我的文章"
  logout: "退出登录"
  searchph:  "查找内容。。"
  searchbtn: "查找"
  dashboard: "控制台"
  albums: "专辑管理"
  articles: "文章管理"
  tags: "标签管理"
  users: "用户管理"

  loginbtn: "登录"
  resetbtn: "重置"
  emailph: "输入完整的邮件地址,例如:helloworld@gmai.com"
  passwdph: "输入密码！"
  passwderr: "用户不存在或者密码错误."

  image: "图片"
  url: "链接"
  success: "成功"
  error: "错误"
  named: "命名"
  close: "关闭"
  cancel: "取消"
  save: "保存"
  operate: "操作"
  public: "公开"
  private: "私有"

  articlenew: "新文章"
  articletitle: "文章标题"
  articlestatus: "状态"
  articleauthor: "文章作者"
  articlesortby: "排序"
  articleoperatedel: "删除"
  articlelastmodify: "最后修改"
  articlepublishstatus: "发布状态"
  articlecreatetime: "创建时间"
  articletagpublished: "已发布"
  articletagdraft: "草稿"
  articletagsinglepage: "独立页面"
  articleoperateedit: "编辑"
  articlealbums: "加入专辑"
  articleviewswich: "预览开关"
  articlesavedraft: "存草稿"
  articlesavepublished: "发布"
  articlesavepublishedsinglepage: "发布独立页面"
  articlelastsave: "最后保存"
  articlecontentph: "此处输入文章内容,支持markdown"
  articletagsph: "单个文章最多五个标签"
  articletitleph: "在这里输入文章标题"
  articleinsert: "插入＋"
  articleinsertcontent: "插入内容"

  albumnew: "新专辑"
  albumedit: "编辑专辑"
  albumname: "专辑名称"
  albumpubliced: "是否公开"
  albumauthor: "专辑创建者"
  albumcreateat: "创建时间"
  albumusedcount: "文章总数"


  tagalready: "选择标签"